// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUalkqQJlMBfyH7-3n3YsVtI4kG-H1CA',
    appId: '1:155121309760:web:36da029bae2168bc5f67a5',
    messagingSenderId: '155121309760',
    projectId: 'arkeonil',
    authDomain: 'arkeonil.firebaseapp.com',
    storageBucket: 'arkeonil.appspot.com',
    measurementId: 'G-DXQSJ6B3CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA75PAsU9dpilMp0Lt8rp7i_VG7qmR1IeU',
    appId: '1:155121309760:android:5bc4072415e922e15f67a5',
    messagingSenderId: '155121309760',
    projectId: 'arkeonil',
    storageBucket: 'arkeonil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF9q4e2Ibcz7n9XqgFNMQfohhujBzS9H8',
    appId: '1:155121309760:ios:0257bd75d5f308405f67a5',
    messagingSenderId: '155121309760',
    projectId: 'arkeonil',
    storageBucket: 'arkeonil.appspot.com',
    iosBundleId: 'com.example.arkeonil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF9q4e2Ibcz7n9XqgFNMQfohhujBzS9H8',
    appId: '1:155121309760:ios:41f7621346eff4ab5f67a5',
    messagingSenderId: '155121309760',
    projectId: 'arkeonil',
    storageBucket: 'arkeonil.appspot.com',
    iosBundleId: 'com.example.arkeonil.RunnerTests',
  );
}
